import {Noto_Sans_JP} from 'next/font/google'

// ここで全ページ共通のフォントを定義する
const NotoSansJP = Noto_Sans_JP({
    weight: ["400", "700"],
    subsets: ["latin"],
    preload: true,
});

// ここで全ページ共通のレイアウトを定義する
export const metadata = {
    title: 'Next.js Awesome Memo App',
    description: 'Generated by create next app',
}

// 全ページ共通のレイアウト
export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ja">
        <body className={NotoSansJP.className}>{children}</body>
        </html>
    )
}